import { TokenIdentifier } from './NFT.model';

interface NotificationsSettings {
	email?: string;
  LISTING_CREATED_PENDING: boolean, // done
  LISTING_CREATED_CANCELLED: boolean, // done
  LISTING_CREATED_COMPLETED: boolean, //done
  LISTING_CREATED_ERROR: boolean, // done

  OFFER_CREATED_PENDING: boolean, // done
  OFFER_CREATED_CANCELLED: boolean, // done
  OFFER_CREATED_COMPLETED: boolean, // done
  OFFER_CREATED_ERROR: boolean, // done

  OFFER_RECEIVED: boolean, // done

  LISTING_PURCHASED_OLD_OWNER: boolean, // done
  LISTING_PURCHASED_NEW_OWNER: boolean, // done
  LISTING_PURCHASED_ERROR: boolean, // done

  OFFER_ACCEPTED_OLD_OWNER: boolean, // done
  OFFER_ACCEPTED_NEW_OWNER: boolean, // done
  OFFER_ACCEPTED_ERROR: boolean, // done

  REMOVE_LISTING_PENDING: boolean, // done
  REMOVE_LISTING_CANCELLED: boolean, // done
  REMOVE_LISTING_COMPLETED: boolean, // done
  REMOVE_LISTING_ERROR: boolean,

  REMOVE_OFFER_PENDING: boolean, // done
  REMOVE_OFFER_CANCELLED: boolean, // done
  REMOVE_OFFER_COMPLETED: boolean, // done
  REMOVE_OFFER_ERROR: boolean // done
}

enum NOTIFICATION_CODES {
  VERIFF_STARTED = 201,
  VERIFF_SUBMITTED = 202,
  VERIFF_POSITIVE = 203,
  VERIFF_NEGATIVE = 204,
  VERIFF_RESUBMITTED = 205,
  VERIFF_EXPIRED = 206,
  VERIFF_REVIEW = 207,

  LISTING_CREATED = 100,
  OFFER_CREATED = 101,

  LISTING_REMOVED = 110,
  OFFER_REMOVED = 111,

  OFFER_RECEIVED = 120,
  OFFER_OUTBID = 121,

  OFFER_ACCEPTED_NEW_OWNER = 130,
  OFFER_ACCEPTED_OLD_OWNER = 131,
  LISTING_PURCHASED_OLD_OWNER = 132,
  LISTING_PURCHASED_NEW_OWNER = 133,

  WINE_CHANGED = 140,
}

enum TXN_STATUS {
  TRANSACTION_PENDING = 500,
  TRANSACTION_CANCELLED = 501,
  TRANSACTION_COMPLETED = 502,
  TRANSACTION_ERROR = 503,
}

enum VERIFF_NOTIFICATION_STATUS {
  STARTED = 7001,
  SUBMITTED = 7002,
  POSITIVE = 9001,
  NEGATIVE = 9102,
  RESUBMITTED = 9103,
  EXPIRED = 9104,
  REVIEW = 9121,
}

const NotificationSettingCodeEnum = {
  LISTING_CREATED_PENDING: `${NOTIFICATION_CODES.LISTING_CREATED}:${TXN_STATUS.TRANSACTION_PENDING}`,
  LISTING_CREATED_CANCELLED: `${NOTIFICATION_CODES.LISTING_CREATED}:${TXN_STATUS.TRANSACTION_CANCELLED}`,
  LISTING_CREATED_COMPLETED: `${NOTIFICATION_CODES.LISTING_CREATED}:${TXN_STATUS.TRANSACTION_COMPLETED}`,
  LISTING_CREATED_ERROR: `${NOTIFICATION_CODES.LISTING_CREATED}:${TXN_STATUS.TRANSACTION_ERROR}`,

  OFFER_CREATED_PENDING: `${NOTIFICATION_CODES.OFFER_CREATED}:${TXN_STATUS.TRANSACTION_PENDING}`,
  OFFER_CREATED_CANCELLED: `${NOTIFICATION_CODES.OFFER_CREATED}:${TXN_STATUS.TRANSACTION_CANCELLED}`,
  OFFER_CREATED_COMPLETED: `${NOTIFICATION_CODES.OFFER_CREATED}:${TXN_STATUS.TRANSACTION_COMPLETED}`,
  OFFER_CREATED_ERROR: `${NOTIFICATION_CODES.OFFER_CREATED}:${TXN_STATUS.TRANSACTION_ERROR}`,

  OFFER_RECEIVED: `${NOTIFICATION_CODES.OFFER_RECEIVED}:${TXN_STATUS.TRANSACTION_COMPLETED}`,

  LISTING_PURCHASED_OLD_OWNER: `${NOTIFICATION_CODES.LISTING_PURCHASED_OLD_OWNER}:${TXN_STATUS.TRANSACTION_COMPLETED}`,
  LISTING_PURCHASED_NEW_OWNER: `${NOTIFICATION_CODES.LISTING_PURCHASED_NEW_OWNER}:${TXN_STATUS.TRANSACTION_COMPLETED}`,
  LISTING_PURCHASED_ERROR: `${NOTIFICATION_CODES.LISTING_PURCHASED_NEW_OWNER}:${TXN_STATUS.TRANSACTION_ERROR}`,

  OFFER_ACCEPTED_OLD_OWNER: `${NOTIFICATION_CODES.OFFER_ACCEPTED_OLD_OWNER}:${TXN_STATUS.TRANSACTION_COMPLETED}`,
  OFFER_ACCEPTED_NEW_OWNER: `${NOTIFICATION_CODES.OFFER_ACCEPTED_NEW_OWNER}:${TXN_STATUS.TRANSACTION_COMPLETED}`,
  OFFER_ACCEPTED_ERROR: `${NOTIFICATION_CODES.OFFER_ACCEPTED_NEW_OWNER}:${TXN_STATUS.TRANSACTION_ERROR}`,

  REMOVE_LISTING_PENDING: `${NOTIFICATION_CODES.LISTING_REMOVED}:${TXN_STATUS.TRANSACTION_PENDING}`,
  REMOVE_LISTING_CANCELLED: `${NOTIFICATION_CODES.LISTING_REMOVED}:${TXN_STATUS.TRANSACTION_CANCELLED}`,
  REMOVE_LISTING_COMPLETED: `${NOTIFICATION_CODES.LISTING_REMOVED}:${TXN_STATUS.TRANSACTION_COMPLETED}`,
  REMOVE_LISTING_ERROR: `${NOTIFICATION_CODES.LISTING_REMOVED}:${TXN_STATUS.TRANSACTION_ERROR}`,

  REMOVE_OFFER_PENDING: `${NOTIFICATION_CODES.OFFER_REMOVED}:${TXN_STATUS.TRANSACTION_PENDING}`,
  REMOVE_OFFER_CANCELLED: `${NOTIFICATION_CODES.OFFER_REMOVED}:${TXN_STATUS.TRANSACTION_CANCELLED}`,
  REMOVE_OFFER_COMPLETED: `${NOTIFICATION_CODES.OFFER_REMOVED}:${TXN_STATUS.TRANSACTION_COMPLETED}`,
  REMOVE_OFFER_ERROR: `${NOTIFICATION_CODES.OFFER_REMOVED}:${TXN_STATUS.TRANSACTION_ERROR}`,

  VERIFF_STARTED: `${NOTIFICATION_CODES.VERIFF_STARTED}:${VERIFF_NOTIFICATION_STATUS.STARTED}`,
  VERIFF_SUBMITTED: `${NOTIFICATION_CODES.VERIFF_SUBMITTED}:${VERIFF_NOTIFICATION_STATUS.SUBMITTED}`,
  VERIFF_POSITIVE: `${NOTIFICATION_CODES.VERIFF_POSITIVE}:${VERIFF_NOTIFICATION_STATUS.POSITIVE}`,
  VERIFF_NEGATIVE: `${NOTIFICATION_CODES.VERIFF_NEGATIVE}:${VERIFF_NOTIFICATION_STATUS.NEGATIVE}`,
  VERIFF_RESUBMITTED: `${NOTIFICATION_CODES.VERIFF_RESUBMITTED}:${VERIFF_NOTIFICATION_STATUS.RESUBMITTED}`,
  VERIFF_EXPIRED: `${NOTIFICATION_CODES.VERIFF_EXPIRED}:${VERIFF_NOTIFICATION_STATUS.EXPIRED}`,
  VERIFF_REVIEW: `${NOTIFICATION_CODES.VERIFF_REVIEW}:${VERIFF_NOTIFICATION_STATUS.REVIEW}`,
} as const;

interface NotificationSchema {
  link?: string;
}

interface TransactionNotificationModel
  extends NotificationSchema,
    TokenIdentifier {
  status: TXN_STATUS;
  orderPrice?: string;
  orderCurrency?: string;
  brand: string;
}

interface VeriffNotificationModel extends NotificationSchema {
  status: VERIFF_NOTIFICATION_STATUS;
  text: string;
}

interface NotificationReceived {
  walletAddress: string;
  code: NOTIFICATION_CODES;
  message: string;
  dateCreated: number;
}

type ExtendedNotificationModel<T> = T extends 'transaction'
  ? NotificationReceived & TransactionNotificationModel
  : T extends 'veriff'
  ? NotificationReceived & VeriffNotificationModel
  : NotificationReceived;

interface FetchNotificationsRequest {
  walletAddress: string;
  order: 'earliest' | 'latest';
  filter: 'all' | 'offers' | 'sale';
  apiKey: string;
}

export {
  NOTIFICATION_CODES,
  NotificationReceived,
  TransactionNotificationModel,
  VeriffNotificationModel,
  ExtendedNotificationModel,
  TXN_STATUS,
  NotificationsSettings,
  FetchNotificationsRequest,
  NotificationSettingCodeEnum
};
